# Generated by Django 5.0.2 on 2024-03-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pd_IndexNumber', models.BigAutoField(primary_key=True, serialize=False)),
                ('Pd_name', models.CharField(max_length=255)),
                ('Pd_Price', models.IntegerField()),
                ('Pd_Market', models.CharField(max_length=10)),
                ('Pd_IMG', models.CharField(max_length=500)),
                ('Pd_URL', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
