# Generated by Django 5.0.2 on 2024-03-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Pd_Price',
            field=models.BigIntegerField(),
        ),
    ]
