# Generated by Django 5.0.2 on 2024-03-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_handlingduplicates_alter_product_pd_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandlingDuplicates',
        ),
    ]
